# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clust <- function(x, k, w, sort) {
    .Call(`_oneclust_clust`, x, k, w, sort)
}

